GCOV_PROFILE := y
EXTRA_CFLAGS += -Idrivers/video/tegra/host
EXTRA_CFLAGS += $(call cc-option,-Wno-error=address-of-packed-member)
obj-y += dev.o
obj-y += util.o
obj-y += cursor.o
obj-y += events.o
obj-y += control.o
